# Generated by Django 3.0.7 on 2020-06-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('school_name', models.CharField(max_length=10)),
                ('mother', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Student',
            },
        ),
    ]
