# Generated by Django 3.0.7 on 2020-06-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AlterModelTable(
            name='student',
            table=None,
        ),
    ]
